$('.pim').click(function() {
	$('.pim').addClass('active');
	$('.pim > .icon').addClass('active');
	$('.about').removeClass('active');
	$('.history').removeClass('active');
	$('.secure').removeClass('active');
	$('.upload').removeClass('active');
	$('.about > .icon').removeClass('active');
	$('.history > .icon').removeClass('active');
	$('.secure > .icon').removeClass('active');
	$('.upload > .icon').removeClass('active');
	$('#line').addClass('one');
	$('#line').removeClass('two');
	$('#line').removeClass('three');
	$('#line').removeClass('four');
	$('#line').removeClass('five');
});
$('.history').click(function() {
	$('.history').addClass('active');
	$('.history > .icon').addClass('active');
	$('.pim').removeClass('active');
	$('.secure').removeClass('active');
	$('.upload').removeClass('active');
	$('.about').removeClass('active');
	$('.about > .icon').removeClass('active');
	$('.pim > .icon').removeClass('active');
	$('.secure > .icon').removeClass('active');
	$('.upload > .icon').removeClass('active');
	$('#line').addClass('two');
	$('#line').removeClass('one');
	$('#line').removeClass('three');
	$('#line').removeClass('four');
	$('#line').removeClass('five');
});
$('.secure').click(function() {
	$('.secure').addClass('active');
	$('.secure > .icon').addClass('active');
	$('.history').removeClass('active');
	$('.pim').removeClass('active');
	$('.upload').removeClass('active');
	$('.about').removeClass('active');
	$('.about > .icon').removeClass('active');
	$('.history > .icon').removeClass('active');
	$('.pim > .icon').removeClass('active');
	$('.upload > .icon').removeClass('active');
	$('#line').addClass('three');
	$('#line').removeClass('two');
	$('#line').removeClass('one');
	$('#line').removeClass('four');
	$('#line').removeClass('five');
});
$('.upload').click(function() {
	$('.upload').addClass('active');
	$('.upload > .icon').addClass('active');
	$('.history').removeClass('active');
	$('.secure').removeClass('active');
	$('.pim').removeClass('active');
	$('.about').removeClass('active');
	$('.about > .icon').removeClass('active');
	$('.history > .icon').removeClass('active');
	$('.secure > .icon').removeClass('active');
	$('.pim > .icon').removeClass('active');
	$('#line').addClass('four');
	$('#line').removeClass('two');
	$('#line').removeClass('three');
	$('#line').removeClass('one');
	$('#line').removeClass('five');
});
$('.about').click(function() {
	$('.about').addClass('active');
	$('.about > .icon').addClass('active');
	$('.upload').removeClass('active');
	$('.history').removeClass('active');
	$('.secure').removeClass('active');
	$('.pim').removeClass('active');
	$('.upload > .icon').removeClass('active');
	$('.history > .icon').removeClass('active');
	$('.secure > .icon').removeClass('active');
	$('.pim > .icon').removeClass('active');
	$('#line').addClass('five');
	$('#line').removeClass('four');
	$('#line').removeClass('two');
	$('#line').removeClass('three');
	$('#line').removeClass('one');
});
$('.pim').click(function() {
	$('#first').addClass('active');
	$('#second').removeClass('active');
	$('#third').removeClass('active');
	$('#fourth').removeClass('active');
	$('#fifth').removeClass('active');
});
$('.history').click(function() {
	$('#first').removeClass('active');
	$('#second').addClass('active');
	$('#third').removeClass('active');
	$('#fourth').removeClass('active');
	$('#fifth').removeClass('active');
});
$('.secure').click(function() {
	$('#first').removeClass('active');
	$('#second').removeClass('active');
	$('#third').addClass('active');
	$('#fourth').removeClass('active');
	$('#fifth').removeClass('active');
});
$('.upload').click(function() {
	$('#first').removeClass('active');
	$('#second').removeClass('active');
	$('#third').removeClass('active');
	$('#fourth').addClass('active');
	$('#fifth').removeClass('active');
});
$('.about').click(function() {
	$('#first').removeClass('active');
	$('#second').removeClass('active');
	$('#third').removeClass('active');
	$('#fourth').removeClass('active');
	$('#fifth').addClass('active');
});
